server:
  port: 8000
  address: 127.0.0.1
  servlet:
    context-path: /spike

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.60.38.54:3306/mysql?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 656803
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  ldap:
    urls: #ldaps://xxx.xxx.com:636
    username: #CN=xx,OU=xx,OU=ITSSC,OU=xx,OU=AdminUnits,DC=xx,DC=xx,DC=com
    password: #xxx
    base: #DC=xx,DC=xx,DC=xxx
  mail:
    host: smtp.qq.com
    port: 465
    username: 2926169741@qq.com #初始邮件地址（发送邮件者）
    password: ouiejfkeeypndccd  #密码
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            socketFactory:
              class: com.sun.mail.util.MailSSLSocketFactory
              fallback: false
  #其他数据库
  lvBaseData:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL
    url: jdbc:mysql://127.0.0.1:3306/cloudpivot?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false   # MySQL
    username: root
    password: 123456
  #redis
  redis:
    host: 123.60.38.54
    port: 6379
    timeout: 20000
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
    password: 656803



logging:
  level:
    com.lzj.admin.mapper: debug

  pattern:
    console: '%d{2100-01-01 13:14:00.666} [%thread] %-5level %logger{50} - %msg%n'




